### ISSUE TITLE
Support for Py3

### ISSUE THREAD

**Issue by vkruoso** [robotframework/robotbackgroundlogger#3]
This issue is to map tests to verify this module supports Python 3.

**Comment by vkruoso** [comment]
@pekkaklarck Can you review pull request #4 for this issue?

**Comment by pekkaklarck** [comment]
This is on my todo list but now that RF 3.0.1 is out I've been planning to look at Se2Lib Py3 support firts. Or is really simple PR to review?

**Comment by vkruoso** [comment]
The PR itself is, just a few changes on print statements. I'm not sure about any CI on this repo that may be altered.

**Comment by pekkaklarck** [comment]
Oh yeah, the PR is trivial. Was on mobile when writing the previous comment. Sorry also for missing this earlier.

**Comment by pekkaklarck** [comment]
PR #4 merged, `from __future__ import print_function` added in 31ee9f98ea681024c80e15b8ac7533466428f604, setup.py updated in b7d2a34574f094592902b8b4185a9f110368676c and README in eeadd9ce289f241bbb2509a03bf3c98f6af6151f.

I haven't really tested Python 3 compatibility, though, and thus I reopen this issue. Can you @vkruoso test Python 3 works fine now? If it does, I can create a new release.

**Comment by pekkaklarck** [comment]
Created 1.2 release today.
